name: release

on:
  release:
    types: 
      - published

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Alpine Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          target: alpine
          tags: |
            poojagangwar/authn-jwt-gitlab:alpine
      - name: Build and push Ubuntu Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          target: ubuntu
          tags: |
            poojagangwar/authn-jwt-gitlab:ubuntu
            poojagangwar/authn-jwt-gitlab:latest
      - name: Build and push UBI-FIPS Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          target: ubi
          tags: |
            poojagangwar/authn-jwt-gitlab:ubi-fips
